[platformio]
default_envs = esp32dev
src_dir = src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -Isrc/esp32/include
build_src_filter =
  +<esp32/**>
  -<**/.history/**>

[env:robomaster_f427ii]
platform = ststm32
board = robomaster_f427ii
framework = stm32cube
build_src_filter =
  +<drivetraincpp/Sources/**>
  +<drivetraincpp/Startup/**>
  -<drivetraincpp/Debug/**>
  -<drivetraincpp/.history/**>
build_flags =
  -DUSE_HAL_DRIVER
  -DSTM32F427xx
  -Isrc/drivetraincpp/Include
board_build.ldscript = src/drivetraincpp/STM32F427IIHX_FLASH.ld
upload_protocol = stlink
debug_tool = stlink
